In [27]:
%pip install numpy

def homework(message, answer = ''):
    print(f'\n❓ {message}\n💡 {answer}\n')


[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 7

print(f"При множенні на 7 маємо: {t1}")
homework("Чому маємо такий результат?", "Все правильно, масив помножився на 7, тобто повторився 7 разів")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне?", "Бо тепер генерується масив в якому кожен елемент помножений на 7")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 7
print("При множенні на 7 отримуємо:", t3)

homework('Цікаво )', 'Так )')

[20.1, 20.1, 20.2, 20.4]
При множенні на 7 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

❓ Чому маємо такий результат?
💡 Все правильно, масив помножився на 7, тобто повторився 7 разів

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

❓ Чому тепер множення успішне?
💡 Бо тепер генерується масив в якому кожен елемент помножений на 7

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 7 отримуємо: [140.7 140.7 141.4 142.8]

❓ Цікаво )
💡 Так )



### Робота з векторами

In [29]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")

vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])

print(f'Вектор має розмір {vector_row.shape} \n{vector_row}\n')
print(f'Вектор має розмір {vector_column.shape} \n{vector_column}\n')

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
Вектор має розмір (1, 5) 
[[ 1 -5  3  2  4]]

Вектор має розмір (4, 1) 
[[1]
 [2]
 [3]
 [4]]



### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [30]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
homework("Виведіть весь діапазон чисел.", a)

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework("Виведіть останній діапазон в згенерованому масиві.", a[-1])

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", [0], )
homework("Виведіть якесь число з середини діапазону.", x[13])

# дробові числа
x = np.arange(10.4)
print("Будем мати:", x)

# крок
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)

# Заокруглення
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зерніть уагу на заокруглення")

vec = np.arange( 0.00001, 0.0001, 0.00001)
homework("Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?", vec)

y = x * 2.5
print("Після перемноження:", y)

res = (y ** 2) / 0.4
homework("Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?", res)

Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]

❓ Виведіть весь діапазон чисел.
💡 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Можемо задавати початок генерації вектора, перший елемент: 5

❓ Виведіть останній діапазон в згенерованому масиві.
💡 99

Те саме але з вбудованою функцією range: range(5, 100)
Власне вивід значень: [0]

❓ Виведіть якесь число з середини діапазону.
💡 18

Будем мати: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
З кроком 0.5: [0.5 1.  1.5 2.  2.5 3.  3.5]
З кроком 0.08: [0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ] 
 Зерніть уагу на заокруглення

❓ Згенеруйте значення де крок буде мати чотири нулі після ко

### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [33]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
#print(f"Власне числа: {a}")

a2 = list()
for i in range(0, len(a), 2):
    a2.append(a[i])

homework("Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)", a2)

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")

print('Кількість чисел 100:')
a = np.linspace(start, size_of_vec, 100)
print(a)
print('Перші 10:\n', a[0:10])
print('Останні 10:\n', a[-10:])
print()

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Спробуйте самі порахуавти крок.", "Здається крок 19. Це чому так 🤔 ") 

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
print(_)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(_)

print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
homework("Чому маємо такий крок?", "Трошки дивна штука\n   В другому випадку виходить 95 елемнтів.")

Згенерували 50 чисел в діапазоні 5.0 до 100.0

❓ Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)
💡 [5.0, 8.877551020408163, 12.755102040816325, 16.632653061224488, 20.51020408163265, 24.387755102040817, 28.26530612244898, 32.14285714285714, 36.0204081632653, 39.89795918367347, 43.775510204081634, 47.6530612244898, 51.53061224489796, 55.40816326530612, 59.285714285714285, 63.16326530612245, 67.0408163265306, 70.91836734693878, 74.79591836734694, 78.6734693877551, 82.55102040816327, 86.42857142857143, 90.3061224489796, 94.18367346938776, 98.06122448979592]

Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]

❓ Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.
💡 

Кількість чисел 100:
[  5.           5.95959596   6.91919192   7.87878788   8.83838384
   9.7979798   10.75757576  11.71717172  12.67676768  13.63636364
  14.5959596   15.55555556  16.51515152  17.47474747  18.43434343
  19.39393939  20.35353535  21.31313131  

### Типи масивів/векторів

In [ ]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ]),
    'Дуужее Багатовимірна Матриця з 1 елементом )': np.array([[[[[[[[[[1]]]]]]]]]])
    }

for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задайте власні вектори з різними числами.""", "np.ndim повертає глибину масиву, тобто кількість вимірів, а метод shape повертає форму ")

Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

### Багатовимірні масиви, розуміння вимірів

In [ ]:
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
    }

for a in examples:
    print(f"Для {a} маємо shape: {examples[a].shape} \nта вигляд: \n{examples[a]}\n")

homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

shps = {
    'Квадрат' : np.array([[1, 2],[3, 4]]),
    'Куб' : np.array([[[1, 2],[3, 4]], [[5, 6], [7, 8]]])
}

for s in shps:
    print(f"{s}\n{shps[s].shape}\n{shps[s]}\n")

Для 5 рядків маємо shape: (5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]

Для 5 стовпців маємо shape: (1, 5) 
та вигляд: 
[[1 2 3 4 5]]

Для 5 елементів маємо shape: (1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]


❓ Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.
💡 

Квадрат
(2, 2)
[[1 2]
 [3 4]]

Куб
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



### Indexing and Slicing

In [ ]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")

array = [ i for i in range(10) ]
print(f'{array = }')
print(array[0]) # виводить 1 елем
print(array[:0]) # виводить 0 елементів )
print(array[6:]) # виводить елементи з 6
print(array[3:6]) # виводить з 3 по 6 елем
print(array[::]) # виводить всі елементи
print(array[0:10:2]) # ого, воно виводить кожен 2 елемент починаючи з 0 і до 10



Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 1
Другий:
 1
Останній, 8: 
 21
Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 21
Передостанній:
 13

❓ Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.
💡 

array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0
[]
[6, 7, 8, 9]
[3, 4, 5]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


In [ ]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")

print(A[0][0])
print(A[1][1])
print(A[2][1])
print(A[-1][-1])

Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1


❓ Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.
💡 

3.4
-7.8
12.3
5.1


In [ ]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")

print(S[4:9])

Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


❓ Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.
💡 

[4 5 6 7 8]


In [ ]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")

homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")

print(f'''
Верхній лівий:
{A[0:2, 0:2]}

Верхній правий:
{A[0:2, -2:5]}

Нижній правий:
{A[-2:, -2:]}

Нижній лівий:
{A[-2:, 0:2]}
''')


Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]


❓ Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.
💡 


Верхній лівий:
[[11 12]
 [21 22]]

Верхній правий:
[[14 15]
 [24 25]]

Нижній правий:
[[44 45]
 [54 55]]

Нижній лівий:
[[41 42]
 [51 52]]



In [ ]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожномуу другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")

homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")

print(f'Кожен 1 елемент з всіх рядків\n{A[::1, 0]}')

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен дугий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожномуу другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повнісню змінити порядок елементів (дзерально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


❓ Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.
💡 

Кожен 1 елемент з всіх рядків
[ 0  7 14 21]


In [ ]:
A = np.arange(50)
all_even = (A%2==0) # парні
complex = (A<30) & (A/5<2) 

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порінянь:
{A[complex]}""")

homework("Виведіть всі непарні числа з даного масиву.")

all_not_even = (A%2==1)
print(f'Всі не парні:\n {A[all_not_even]}')

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порінянь:
[0 1 2 3 4 5 6 7 8 9]

❓ Виведіть всі непарні числа з даного масиву.
💡 

Всі не парні:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [ ]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")


Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[0. 0. 0. 0. 0.]

