In [1]:
import numpy as np

def homework(message):
    print("\n>>>>>", message)

def answer(message):
    print("<<<<<", message, "\n")

# Операції над масивами

In [2]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")

homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")


E = np.eye(3)
O = np.ones((3, 3))

print(f"""
Масив око: \n {E}

Порівняння на наявність 1: \n {E == 1}

Одиниці: \n {O}

O - E: \n {O - E}
""")



Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.60131837 0.31243335 0.09669291]
 [0.28835093 0.76775705 0.04303787]
 [0.65458926 0.56897702 0.71212086]]
Ділення:
 [[       inf 0.31243335 0.04834646]
 [       inf 0.76775705 0.02151894]
 [       inf 0.56897702 0.35606043]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True False False]
 [False  True False]
 [ True  True  True]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).


Масив око: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Порівняння на наявність 1: 
 [[ True False False]
 [False  True False]
 [False False  True]]

Одиниці: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

O - E: 
 [[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]



C:\Users\HP FOLIO 9480M\AppData\Local\Temp\ipykernel_17016\3231747390.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\HP FOLIO 9480M\AppData\Local\Temp\ipykernel_17016\3231747390.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


# Множення матриць

In [3]:
A = np.array([ [1, 2, 5], [2, 2, 2], [5, 5, 5] ])
B = np.array([ [5, 2, 1], [1, 2, 4], [-1, -2, -4] ])
print(f"Маємо два масиви:\n {A} \n\n {B}")

R = A * B
print(f"\nТут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"\nТут, масиви перемножуються як матриці:\n {R}")

MA = np.mat(A)
MB = np.mat(B)

R = MA * MB
print(f"\nТут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 5]
 [2 2 2]
 [5 5 5]] 

 [[ 5  2  1]
 [ 1  2  4]
 [-1 -2 -4]]

Тут виконується поелементне множення:
 [[  5   4   5]
 [  2   4   8]
 [ -5 -10 -20]]

Тут, масиви перемножуються як матриці:
 [[  2  -4 -11]
 [ 10   4   2]
 [ 25  10   5]]

Тут масиви перетворені на матриці і далі перемножуються:
 [[  2  -4 -11]
 [ 10   4   2]
 [ 25  10   5]]


# Вирівнювання розмірностей

In [4]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)

In [5]:
D = np.ones(3)
Z = np.zeros((3,1))

print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
Для конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можем виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")


homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не спаівпадє використайте reshape.
Створіть декіль двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінції reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
""")

###
arr = np.arange(1, 17)
arr = arr.reshape((4,4))
print(f"""
Масив:
{arr}

Конкатикація:
{np.concatenate((arr, arr))}

Повторення:
{np.tile(arr, (2, 2))}

""")
###

###
arr2 = np.arange(1, 17)
arr2 = arr2.reshape((2,8))
print(arr2)
arr2 = arr2.reshape(4, 4)
print(np.concatenate((arr, arr2)))
###

###
print(f"""

{np.ones((1,12))}

{np.ones((2,6))}

{np.ones((3,4))}

{np.ones((4,3))}

{np.ones((6,2))}

{np.ones((12,1))}
""")






При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [1 2 3] розмірністю (3,):
[1. 2. 3. 1. 1. 1.]
Для конкатенації з С
[[1]
 [2]
 [3]]
де С має розмірність = (3, 1) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можем виконати конкатенацію:
[[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]
При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [11 12 13 21 22 23 31 32 33] з розмірністю (9,)


>>>>> Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кіль

# Трансформації масивів

In [6]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")

vec = np.arange(12)

print(f"""
Вектор:
{vec}

shape - {vec.shape}
size - {vec.size}
ndim - {np.ndim(vec)}


Вектор тепер матриця:
{vec.reshape(3, 2, 2)}

Транспонована матриця:
{vec.reshape(3, 2, 2).transpose()}

Транспонована та обернена матриця:
{np.flip(vec.reshape(3, 2, 2).transpose())}

Тепер матриця знову вектор:
{np.flip(vec.reshape(3, 2, 2).transpose()).flatten()}
""")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);


Вектор:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

shape - (12,)
size - 12
ndim - 1


Вектор тепер матриця:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

Транспонована матриця: